version: '3.9'

services:
  app:
    build:
      context: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./botanical-garden-api:/botanical-garden-api
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=django-user
      - DB_PASSWORD=changeme
    depends_on:
      - db

  db:
    image: postgres:alpine3.16
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=django-user
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data:
