# Generated by Django 3.2.12 on 2022-04-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news',
            new_name='context',
        ),
    ]
