# Generated by Django 3.2.12 on 2022-04-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_news_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
