# Generated by Django 3.2.12 on 2022-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220430_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hashtag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
