# Generated by Django 3.2.15 on 2022-09-02 08:47

from django.db import migrations, models
import excursion.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='date',
            field=models.DateTimeField(validators=[excursion.models.validate_excursion_date]),
        ),
    ]
