# Generated by Django 3.2.15 on 2022-09-10 11:34

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[news.models.validate_hashtag])),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='news',
            name='hashtag',
            field=models.ManyToManyField(to='news.Hashtag'),
        ),
    ]
