# Generated by Django 3.2.15 on 2022-09-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220910_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
