# Generated by Django 3.2.12 on 2022-05-10 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion_date', models.DateTimeField()),
                ('excursion_type', models.CharField(choices=[('Індивідуальні відвідування', 'Індивідуальні відвідування'), ('Екскурсія для дорослих', 'Екскурсія для дорослих'), ('Екскурсія для дітей', 'Екскурсія для дітей'), ('Проведення заходів', 'Проведення заходів'), ('Фото - відеозйомки', 'Фото - відеозйомки')], max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
