# Generated by Django 3.2.12 on 2022-05-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='excursion_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='excursion_date',
            field=models.DateField(null=True),
        ),
    ]
