# Generated by Django 3.2.12 on 2022-05-11 08:24

from django.db import migrations, models
import excursion.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0002_auto_20220511_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='user',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='excursion_date',
            field=models.DateField(null=True, validators=[excursion.models.validate_date]),
        ),
    ]
