# Generated by Django 3.2.12 on 2022-05-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220506_0825'),
        ('excursion', '0003_auto_20220511_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
