# Generated by Django 3.2.12 on 2022-05-12 04:55

from django.db import migrations, models
import excursion.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0004_alter_excursion_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='excursion_time',
            field=models.TimeField(null=True, validators=[excursion.models.validate_time]),
        ),
    ]
