# Generated by Django 3.2.12 on 2022-05-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0005_alter_excursion_excursion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='excursion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='excursion_time',
            field=models.TimeField(null=True),
        ),
    ]
