# Generated by Django 3.2.12 on 2022-07-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0007_auto_20220526_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='excursion_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='excursion_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='excursion_type',
            new_name='type',
        ),
    ]
