# Generated by Django 3.2.12 on 2022-07-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0009_alter_excursion_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='person',
            new_name='user',
        ),
    ]
